services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
    - testing_net
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - ping
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: none
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/main.py
    volumes:
    - ./gateway/config.ini:/app/config.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - testing_net
    healthcheck:
      test:
      - CMD
      - test
      - -f
      - /tmp/gateway_ready
      interval: 5s
      timeout: 5s
      retries: 10
  filter_cleanup:
    container_name: filter_cleanup
    image: filter_cleanup:latest
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/cleanup/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  filter_year:
    container_name: filter_year
    image: filter_year:latest
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/year/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  filter_production:
    container_name: filter_production
    image: filter_production:latest
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/production/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  sentiment_analyzer:
    container_name: sentiment_analyzer
    image: sentiment_analyzer:latest
    entrypoint: python3 /app/sentiment_analyzer.py
    volumes:
    - ./sentiment_analyzer/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  join_table:
    container_name: join_table
    image: join_table:latest
    entrypoint: python3 /app/join_table.py
    volumes:
    - ./join_table/config.ini:/app/config.ini
    environment:
      JB_CREDITS_NODES: '1'
      JB_RATINGS_NODES: '1'
    depends_on:
      gateway:
        condition: service_healthy
      join_batch_credits_1:
        condition: service_started
      join_batch_ratings_1:
        condition: service_started
    networks:
    - testing_net
  join_batch_credits_1:
    container_name: join_batch_credits_1
    image: join_batch_credits:latest
    entrypoint: python3 /app/join_batch.py
    environment:
      NODE_ID: '1'
    volumes:
    - ./join_batch/credits/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  join_batch_ratings_1:
    container_name: join_batch_ratings_1
    image: join_batch_ratings:latest
    entrypoint: python3 /app/join_batch.py
    environment:
      NODE_ID: '1'
    volumes:
    - ./join_batch/ratings/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  q1:
    container_name: q1
    image: query_q1:latest
    entrypoint: python3 /app/q1.py
    volumes:
    - ./query/q1/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  q2:
    container_name: q2
    image: query_q2:latest
    entrypoint: python3 /app/q2.py
    volumes:
    - ./query/q2/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  q3:
    container_name: q3
    image: query_q3:latest
    entrypoint: python3 /app/q3.py
    volumes:
    - ./query/q3/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  q4:
    container_name: q4
    image: query_q4:latest
    entrypoint: python3 /app/q4.py
    volumes:
    - ./query/q4/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  q5:
    container_name: q5
    image: query_q5:latest
    entrypoint: python3 /app/q5.py
    volumes:
    - ./query/q5/config.ini:/app/config.ini
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /app/main.py
    volumes:
    - ./client/config.ini:/app/config.ini
    - ./resultados:/app/resultados
    environment:
      USE_TEST_DATASET: '0'
    depends_on:
      gateway:
        condition: service_healthy
    networks:
    - testing_net
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
