services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
    - testing_net
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - ping
      interval: 5s
      timeout: 5s
      retries: 5
  gateway:
    container_name: gateway
    image: gateway:latest
    entrypoint: python3 /app/gateway.py
    volumes:
    - ./gateway/config.ini:/app/config.ini
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - testing_net
  join_table:
    container_name: join_table
    image: join_table:latest
    entrypoint: python3 /app/join_table.py
    volumes:
    - ./join_table/config.ini:/app/config.ini
    environment:
      JB_CREDITS_NODES: '1'
      JB_RATINGS_NODES: '1'
    depends_on:
    - gateway
    networks:
    - testing_net
  join_batch_credits_1:
    container_name: join_batch_credits_1
    image: join_batch_credits:latest
    entrypoint: python3 /app/join_batch.py
    volumes:
    - ./join_batch/credits/config.ini:/app/config.ini
    depends_on:
    - gateway
    - join_table
    networks:
    - testing_net
  join_batch_ratings_1:
    container_name: join_batch_ratings_1
    image: join_batch_ratings:latest
    entrypoint: python3 /app/join_batch.py
    volumes:
    - ./join_batch/ratings/config.ini:/app/config.ini
    depends_on:
    - gateway
    - join_table
    networks:
    - testing_net
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
