version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
    - testing_net
  gateway:
    build: ./gateway
    container_name: gateway
    entrypoint: python3 /app/gateway.py
    volumes:
    - ./gateway/config.ini:/app/config.ini
    depends_on:
    - rabbitmq
    networks:
    - testing_net
  filter_cleanup:
    build: ./filter/cleanup
    container_name: filter_cleanup
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/cleanup/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  filter_year:
    build: ./filter/year
    container_name: filter_year
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/year/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  filter_production:
    build: ./filter/production
    container_name: filter_production
    entrypoint: python3 /app/filter.py
    volumes:
    - ./filter/production/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  sentiment_analyzer:
    build: ./sentiment_analyzer
    container_name: sentiment_analyzer
    entrypoint: python3 /app/sentiment_analyzer.py
    volumes:
    - ./sentiment_analyzer/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  join_table:
    build: ./join_table
    container_name: join_table
    entrypoint: python3 /app/join_table.py
    volumes:
    - ./join_table/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  join_batch_credits:
    build: ./join_batch/credits
    container_name: join_batch_credits
    entrypoint: python3 /app/join_batch.py
    volumes:
    - ./join_batch/credits/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  join_batch_ratings:
    build: ./join_batch/ratings
    container_name: join_batch_ratings
    entrypoint: python3 /app/join_batch.py
    volumes:
    - ./join_batch/ratings/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  q1:
    build: ./query/q1
    container_name: q1
    entrypoint: python3 /app/q1.py
    volumes:
    - ./query/q1/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  q2:
    build: ./query/q2
    container_name: q2
    entrypoint: python3 /app/q2.py
    volumes:
    - ./query/q2/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  q3:
    build: ./query/q3
    container_name: q3
    entrypoint: python3 /app/q3.py
    volumes:
    - ./query/q3/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  q4:
    build: ./query/q4
    container_name: q4
    entrypoint: python3 /app/q4.py
    volumes:
    - ./query/q4/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  q5:
    build: ./query/q5
    container_name: q5
    entrypoint: python3 /app/q5.py
    volumes:
    - ./query/q5/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
  client:
    build: ./client
    container_name: client
    entrypoint: python3 /app/client.py
    volumes:
    - ./client/config.ini:/app/config.ini
    depends_on:
    - gateway
    networks:
    - testing_net
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
